name: walletway
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  intl: ^0.19.0
  #tflite: ^1.1.2
  tflite_flutter: ^0.11.0
  provider: ^6.0.3
  image_picker: ^0.8.7+3
  cloud_firestore: ^5.6.0
  shared_preferences: ^2.3.5
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  http: ^1.2.2
  crypto: ^3.0.6
  dartpy: ^0.0.5
  process_run: ^0.12.0
  flutter_keyboard_visibility: ^6.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_radar_chart: ^0.2.1
  #tflite_flutter_helper: ^0.5.0
  #tflite_flutter_plugin: ^0.1.3 # Add this if you haven't already
  awesome_notifications: ^0.10.0  #yahoo_finance_data_reader: ^1.0.0
  telephony: ^0.2.0
  #sms_maintained: ^0.2.4
  permission_handler: ^10.2.0
  #overlay_support: ^1.2.1
  #yahoo_finance_api: ^1.0.5
  fluttertoast: ^8.2.4  # Use the latest version available
  math_expressions: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    #- assets/text_classification_model.tflite
    #- assets/tokenizer.json
    - web/bgw.jpg
  fonts:
    - family: Cookie
      fonts:
        - asset: fonts/Cookie-Regular.ttf
    - family: Alegreya
      fonts:
        - asset: fonts/Alegreya-VariableFont_wght.ttf
